---
title: "IQ-TREE"
output:
  html_document:
    toc: true
    toc_float: true
---


[IQ-TREE](http://www.iqtree.org/) is available as a downloadable program and as an online interface (via web servers).

It is a powerful program that is built for speed! Maximum likelihood methods can consume a lot of compute power, the web interface can do robust analysis in just minutes. 

It has some fantastic documentation with detailed tutorials - see [here](http://www.iqtree.org/doc/).
Current manual available [here](http://www.iqtree.org/doc/iqtree-doc.pdf),

Personally I like to use the web interface, it saves one less program taking up memory on your computer and is super quick!

I like to use the [CIBID, Austria](http://iqtree.cibiv.univie.ac.at/).

Reference for command line options are available [here](http://www.iqtree.org/doc/Command-Reference)

# 1. Input Data

Your alignment file can be `.fasta.`, `.phylip`, `.nexus`

# 2. Subtitution Model Options

Details on subtitution models available [here](http://www.iqtree.org/doc/Substitution-Models)

# 3. Branch Support analysis

...

# 4. IQ-TREE Search Parameters

...